# Generated by Django 5.0 on 2023-12-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thalie', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
